kogito.service.url=http://localhost:8080

# jobs service events based API testing parameters
mp.messaging.outgoing.kogito-job-service-job-request-events.connector=smallrye-kafka
mp.messaging.outgoing.kogito-job-service-job-request-events.topic=kogito-job-service-job-request-events
mp.messaging.outgoing.kogito-job-service-job-request-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer